version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'npm run serve'
        volumes:
            - .:/app
        ports:
            - 8080:8080